version: "3"
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
        test: "/usr/bin/mysql -h --user=root --password=password --execute \"SHOW DATABASES;\""
        interval: 2s
        timeout: 20s
        retries: 10
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydb
  web:
    depends_on:
      - db
    build: .
    ports:
      - "4000:3000"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=mydb